name: deploy-checkout-aws
on:
  push:
    branches: 
      - main
      - f/*
  pull_request:
    branches: [ main ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
jobs:
  test:
    name: Run tests
    id: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Run Terratests
        run: go test -v
        working-directory: ./checkout/tests

  build:
    name: Deploy
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./checkout
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: ./checkout
      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ./checkout
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./checkout
      
#      - name: Terraform Apply
#        id: apply
#        run: terraform apply --auto-approve